<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GastoFijo;
use Illuminate\Support\Facades\DB;

class GastosFijosSeeder extends Seeder
{
    public function run(): void
    {
        // Limpiamos la tabla primero para evitar duplicados si se corre varias veces
        GastoFijo::query()->delete();

        $gastos = [
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'CONDOMINIO',
                'empresa' => 'CONDOMINIO APPTO SALAMAR',
                'fecha' => 'AVISO DE COBRANZAS',
                'costo' => 200,
                'orden' => 4,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'CONDOMINIO',
                'empresa' => 'CONDOMINIO LOCAL PA 14',
                'fecha' => '8',
                'costo' => 150,
                'orden' => 7,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'CONDOMINIO',
                'empresa' => 'CONDOMINIO LOCAL SAMBIL L-94',
                'fecha' => '8 - 15 de cada mes',
                'costo' => 300,
                'orden' => 6,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'CONDOMINIO',
                'empresa' => 'CONDOMINIO MIRASOL',
                'fecha' => '1',
                'costo' => 70,
                'orden' => 8,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'CONDOMINIO',
                'empresa' => 'CONDOMINIO TERRANOVA',
                'fecha' => '8 - 15 de cada mes',
                'costo' => 55,
                'orden' => 0,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'CONDOMINIO',
                'empresa' => 'CONDOMINIO BALCONES',
                'fecha' => '8 - 15 de cada mes',
                'costo' => 10,
                'orden' => 1,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'CONDOMINIO',
                'empresa' => 'CONDOMINIO BALCONES APPTO T4',
                'fecha' => '8 - 15 de cada mes',
                'costo' => 15,
                'orden' => 2,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'CONDOMINIO',
                'empresa' => 'CONDOMINIO TERRAZAS CLUB GOLF',
                'fecha' => '8 - 15 de cada mes',
                'costo' => 25,
                'orden' => 3,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'CONDOMINIO',
                'empresa' => 'CONDOMINIO LOCAL SAMBIL L-26',
                'fecha' => '8 - 15 de cada mes',
                'costo' => 450,
                'orden' => 5,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'ELECTRICIDAD',
                'empresa' => '',
                'fecha' => '',
                'costo' => 0,
                'orden' => 10,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'ELECTRICIDAD',
                'empresa' => 'CORPOELEC CASA PUERTA MARAVEN',
                'fecha' => '1',
                'costo' => 21,
                'orden' => 11,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => '',
                'servicio' => 'INTERNET',
                'empresa' => 'BESSER SOLUTIONS MIRASOL',
                'fecha' => '17',
                'costo' => 28,
                'orden' => 9,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'ALQUILER LOCALES PB-09 PB-10',
                'empresa' => 'DESCARGADORES MARITIMOS',
                'fecha' => '1 - 15 de cada mes',
                'costo' => 1100,
                'orden' => 4,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'ASEO URBANO LOCALES PB-09 Y PB-10',
                'empresa' => 'SUMITCA',
                'fecha' => 'AVISO DE SUMITCA',
                'costo' => 40,
                'orden' => 3,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'CONDOMINIO LOCALES PB-09 Y PB-10',
                'empresa' => 'CONDOMINIO CENTRO COMERCIAL DORAL',
                'fecha' => '8',
                'costo' => 380,
                'orden' => 1,
                'visible' => false,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'ELECTRICIDAD Y RELLENO LOCALES PB-09 Y PB-10',
                'empresa' => 'CORPOELEC / PROTECNIA FALCON',
                'fecha' => '5',
                'costo' => 100,
                'orden' => 2,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'INTERNET LOCALES PB-09 Y PB-10',
                'empresa' => 'AIRTEK',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 30,
                'orden' => 0,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'MERCADO LIBRE',
                'empresa' => 'IMPUESTO MENSUAL POR VENTAS',
                'fecha' => '5',
                'costo' => 40,
                'orden' => 14,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'MONITOREO Y SOPORTE SERVIDOR',
                'empresa' => 'INFORMATICA UNIX',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 50,
                'orden' => 15,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'PUBLICIDAD RADIAL',
                'empresa' => 'HIT FM (LENIS)',
                'fecha' => '1',
                'costo' => 80,
                'orden' => 9,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'PUBLICIDAD RADIAL',
                'empresa' => 'EMIRO BRAVO',
                'fecha' => '15',
                'costo' => 60,
                'orden' => 8,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'PUBLICIDAD RADIAL',
                'empresa' => 'EDUARDO VASQUEZ',
                'fecha' => '24',
                'costo' => 60,
                'orden' => 7,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'PUBLICIDAD REDES',
                'empresa' => 'ZINLI',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 100,
                'orden' => 5,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'PUBLICIDAD REDES',
                'empresa' => 'GEEK ELECTRONICO (ADONIS)',
                'fecha' => '30',
                'costo' => 30,
                'orden' => 6,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'RECARGA TELEFONO CHOFER',
                'empresa' => 'LUIS GARCIA',
                'fecha' => '15',
                'costo' => 10,
                'orden' => 11,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'RECARGA TELEFONO CHOFER',
                'empresa' => 'GREGORIO COLINA',
                'fecha' => '17',
                'costo' => 13,
                'orden' => 12,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'RECARGA TELEFONO REDES',
                'empresa' => 'REDES DORAL',
                'fecha' => '10',
                'costo' => 5,
                'orden' => 13,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'RECARGA TELEFONOS CORPORATIVOS',
                'empresa' => 'CORPORACION DIGITEL',
                'fecha' => '1',
                'costo' => 200,
                'orden' => 10,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. PRINCIPAL J401722296',
                'servicio' => 'TU MARCA CLOUD MAI SERVICES, C.A.',
                'empresa' => 'RICARDO MAITA',
                'fecha' => '',
                'costo' => 55,
                'orden' => 16,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. SUCURSAL SAMBIL J401722296',
                'servicio' => 'ASEO URBANO LOCAL L-114',
                'empresa' => 'SUMITCA',
                'fecha' => 'AVISO DE SUMITCA',
                'costo' => 20,
                'orden' => 18,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. SUCURSAL SAMBIL J401722296',
                'servicio' => 'CONDOMINIO LOCAL L-114',
                'empresa' => 'A.S. 20 PARAGUANÁ, C.A.',
                'fecha' => '31 - 15 de cada mes',
                'costo' => 200,
                'orden' => 17,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. SUCURSAL SAMBIL J401722296',
                'servicio' => 'INTERNET LOCAL L-114',
                'empresa' => 'BESSER SOLUTIONS',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 49.88,
                'orden' => 21,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. SUCURSAL SAMBIL J401722296',
                'servicio' => 'MONITOREO Y SOPORTE SERVIDOR',
                'empresa' => 'INFORMATICA UNIX',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 50,
                'orden' => 20,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'INVERSIONES DORAL PARAGUANÁ, C.A. SUCURSAL SAMBIL J401722296',
                'servicio' => 'RECARGA TELEFONO ENCARGADO SAMBIL',
                'empresa' => 'AURELES LUGO',
                'fecha' => '15',
                'costo' => 5,
                'orden' => 19,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'OFICINAS ADMINISTRACION',
                'servicio' => 'CONDOMINIO LOCAL PA-22',
                'empresa' => 'CONDOMINIO CENTRO COMERCIAL DORAL',
                'fecha' => '8',
                'costo' => 150,
                'orden' => 46,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'OFICINAS ADMINISTRACION',
                'servicio' => 'ELECTRICIDAD Y RELLENO LOCAL PA-22',
                'empresa' => 'CORPOELEC / PROTECNIA FALCON',
                'fecha' => '5',
                'costo' => 100,
                'orden' => 44,
                'visible' => true,
            ],
            [
                'grupo_id' => 0,
                'sede' => 'OFICINAS ADMINISTRACION',
                'servicio' => 'INTERNET LOCAL PA-22',
                'empresa' => 'AIRTEK',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 30,
                'orden' => 45,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'AYUDA',
                'empresa' => 'AGUSTIN JEREZ (PAPA)',
                'fecha' => 'Todos los Viernes',
                'costo' => 400,
                'orden' => 6,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'AYUDA',
                'empresa' => 'MARBETH JEREZ (HERMANA)',
                'fecha' => 'Todos los Lunes',
                'costo' => 400,
                'orden' => 7,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'AYUDA',
                'empresa' => 'MARTA (TIA)',
                'fecha' => 'Todos los Sabados',
                'costo' => 160,
                'orden' => 5,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'COLEGIO CESAR',
                'empresa' => 'CENTRO CIVICO CARDON (U.E. COLEGIO)',
                'fecha' => '',
                'costo' => 140,
                'orden' => 9,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'COLEGIO NAHOMI',
                'empresa' => 'U.E. NUESTRA SEÑORA DEL CARMEN',
                'fecha' => '5',
                'costo' => 120,
                'orden' => 8,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'CONDOMINIO',
                'empresa' => 'CONDOMINIO SAN ROMAN',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 100,
                'orden' => 3,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'INGLES CESAR',
                'empresa' => 'LANGUAGE CENTER',
                'fecha' => '',
                'costo' => 60,
                'orden' => 11,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'INTERNET',
                'empresa' => 'BESSER SOLUTIONS MARIA FATIMA',
                'fecha' => '3',
                'costo' => 25,
                'orden' => 2,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'INTERNET',
                'empresa' => 'BESSER SOLUTIONS DIRECTIVO',
                'fecha' => '3',
                'costo' => 28,
                'orden' => 1,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'NATACION CESAR',
                'empresa' => 'AQUA CLUB',
                'fecha' => '',
                'costo' => 45,
                'orden' => 12,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'POLIZA DE SEGUROS',
                'empresa' => 'MERCANTIL SEGUROS',
                'fecha' => '20',
                'costo' => 225.92,
                'orden' => 4,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'RECARGA TELEFONICA DIGITEL',
                'empresa' => 'ABONO A NRO TLF PERSONAL BS.2000',
                'fecha' => '1',
                'costo' => 20,
                'orden' => 0,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => '',
                'servicio' => 'TAREAS DIRIGIDAS CESAR',
                'empresa' => '',
                'fecha' => '',
                'costo' => 50,
                'orden' => 10,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'EURONISSI, C.A. J412919512 (TIENDA MOVISTAR)',
                'servicio' => 'ASEO URBANO LOCAL M1-2',
                'empresa' => 'SUMITCA',
                'fecha' => 'AVISO DE SUMITCA',
                'costo' => 12,
                'orden' => 57,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'EURONISSI, C.A. J412919512 (TIENDA MOVISTAR)',
                'servicio' => 'CONDOMINIO LOCAL M1-2',
                'empresa' => 'CONDOMINIO CENTRO COMERCIAL VIRTUDES',
                'fecha' => '8 - 15 de cada mes',
                'costo' => 230,
                'orden' => 56,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'EURONISSI, C.A. J412919512 (TIENDA MOVISTAR)',
                'servicio' => 'INTERNET LOCAL M1-2',
                'empresa' => 'BESSER SOLUTIONS',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 67.6,
                'orden' => 59,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'EURONISSI, C.A. J412919512 (TIENDA MOVISTAR)',
                'servicio' => 'MONITOREO Y SOPORTE SERVIDOR',
                'empresa' => 'INFORMATICA UNIX',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 25,
                'orden' => 58,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'GRUPO JRZ TECH ELECTRONICS, C.A. J501653895',
                'servicio' => 'ELECTRICIDAD Y RELLENO DEPÓSITO',
                'empresa' => 'CORPOELEC',
                'fecha' => '1',
                'costo' => 2.5,
                'orden' => 53,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'GRUPO JRZ TECH ELECTRONICS, C.A. J501653895',
                'servicio' => 'INTERNET DEPÓSITO DOÑA EMILIA',
                'empresa' => 'AIRTEK',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 60,
                'orden' => 55,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'GRUPO JRZ TECH ELECTRONICS, C.A. J501653895',
                'servicio' => 'MONITOREO Y SOPORTE SERVIDOR',
                'empresa' => 'INFORMATICA UNIX',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 50,
                'orden' => 54,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. PRINCIPAL J409254852',
                'servicio' => 'ALQUILER LOCAL H-6',
                'empresa' => 'INVERSIONES MILLENIUM',
                'fecha' => '',
                'costo' => 1566,
                'orden' => 27,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. PRINCIPAL J409254852',
                'servicio' => 'ASEO URBANO LOCAL H-6',
                'empresa' => 'SUMITCA',
                'fecha' => 'AVISO DE SUMITCA',
                'costo' => 20,
                'orden' => 23,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. PRINCIPAL J409254852',
                'servicio' => 'CONDOMINIO LOCAL H-12',
                'empresa' => 'CONDOMINIO CENTRO COMERCIAL VIRTUDES',
                'fecha' => '8 - 15 de cada mes',
                'costo' => 300,
                'orden' => 25,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. PRINCIPAL J409254852',
                'servicio' => 'CONDOMINIO LOCAL H-6',
                'empresa' => 'CONDOMINIO CENTRO COMERCIAL VIRTUDES',
                'fecha' => '8 - 15 de cada mes',
                'costo' => 800,
                'orden' => 24,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. PRINCIPAL J409254852',
                'servicio' => 'INTERNET LOCAL H-6',
                'empresa' => 'BESSER SOLUTIONS',
                'fecha' => '15',
                'costo' => 78.88,
                'orden' => 22,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. PRINCIPAL J409254852',
                'servicio' => 'MONITOREO Y SOPORTE SERVIDOR',
                'empresa' => 'INFORMATICA UNIX',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 50,
                'orden' => 26,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL BOLIVAR J409254852',
                'servicio' => 'ALQUILER LOCAL HADI 3000',
                'empresa' => 'MOHAMED NAIMM',
                'fecha' => '1 - 11 de cada mes',
                'costo' => 1600,
                'orden' => 33,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL BOLIVAR J409254852',
                'servicio' => 'ASEO URBANO LOCAL HADI 3000',
                'empresa' => 'SUMITCA',
                'fecha' => 'AVISO DE SUMITCA',
                'costo' => 20,
                'orden' => 30,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL BOLIVAR J409254852',
                'servicio' => 'CUSTODIA LOCAL HADI 3000',
                'empresa' => 'POLICARUBANA',
                'fecha' => 'Todos los Lunes',
                'costo' => 30,
                'orden' => 31,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL BOLIVAR J409254852',
                'servicio' => 'ELECTRICIDAD Y RELLENO LOCAL HADI 3000',
                'empresa' => 'CORPOELEC / PROTECNIA FALCON',
                'fecha' => '5',
                'costo' => 100,
                'orden' => 29,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL BOLIVAR J409254852',
                'servicio' => 'INTERNET LOCAL HADI 3000',
                'empresa' => 'AIRTEK',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 60,
                'orden' => 28,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL BOLIVAR J409254852',
                'servicio' => 'MONITOREO Y SOPORTE SERVIDOR',
                'empresa' => 'INFORMATICA UNIX',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 50,
                'orden' => 32,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL ZAMORA J409254852',
                'servicio' => 'AGUA LOCAL SHANGHAI',
                'empresa' => 'HIDROFALCÓN',
                'fecha' => 'AVISO DEL GESTOR',
                'costo' => 15,
                'orden' => 41,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL ZAMORA J409254852',
                'servicio' => 'ALQUILER LOCAL SHANGHAI',
                'empresa' => 'JESUS SANCHEZ',
                'fecha' => '30',
                'costo' => 450,
                'orden' => 38,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL ZAMORA J409254852',
                'servicio' => 'ASEO URBANO LOCAL SHANGHAI',
                'empresa' => 'SUMITCA',
                'fecha' => 'AVISO DE SUMITCA',
                'costo' => 20,
                'orden' => 40,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL ZAMORA J409254852',
                'servicio' => 'CUSTODIA LOCAL SHANGHAI',
                'empresa' => 'POLICARIRUBANA',
                'fecha' => 'Todos los Lunes',
                'costo' => 30,
                'orden' => 9999,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL ZAMORA J409254852',
                'servicio' => 'ELECTRICIDAD Y RELLENO SHANGHAI',
                'empresa' => 'CORPOELEC / PROTECNIA FALCON',
                'fecha' => '5',
                'costo' => 180,
                'orden' => 39,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL ZAMORA J409254852',
                'servicio' => 'INTERNET LOCAL SHANGHAI',
                'empresa' => 'AIRTEK',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 60,
                'orden' => 43,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL ZAMORA J409254852',
                'servicio' => 'MONITOREO Y SOPORTE SERVIDOR',
                'empresa' => 'INFORMATICA UNIX',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 50,
                'orden' => 42,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL ZAMORA J409254852',
                'servicio' => 'RECARGA TELEFONO CAJA ZAMORA',
                'empresa' => 'CARLOS GOMEZ',
                'fecha' => '14',
                'costo' => 5,
                'orden' => 37,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL ZAMORA J409254852',
                'servicio' => 'RECARGA TELEFONO SUPERVISOR 2 ZAMORA',
                'empresa' => 'AURELES LUGO',
                'fecha' => '13',
                'costo' => 5,
                'orden' => 35,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL ZAMORA J409254852',
                'servicio' => 'RECARGA TELEFONO SUPERVISOR ZAMORA',
                'empresa' => 'CARLOS GOMEZ',
                'fecha' => '14',
                'costo' => 5,
                'orden' => 36,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'LNACEH SPORT, C.A. SUCURSAL ZAMORA J409254852',
                'servicio' => 'RECARGA TELEFONO TELEFONIA ZAMORA',
                'empresa' => 'AURELES LUGO',
                'fecha' => '12',
                'costo' => 5,
                'orden' => 34,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'NUNES STORE, C.A. J501653879',
                'servicio' => 'ASEO URBANO LOCAL L-11 / H-12',
                'empresa' => 'SUMITCA',
                'fecha' => 'AVISO DE SUMITCA',
                'costo' => 20,
                'orden' => 49,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'NUNES STORE, C.A. J501653879',
                'servicio' => 'CONDOMINIO LOCAL H-12',
                'empresa' => 'CONDOMINIO CENTRO COMERCIAL VIRTUDES',
                'fecha' => '8 - 15 de cada mes',
                'costo' => 500,
                'orden' => 52,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'NUNES STORE, C.A. J501653879',
                'servicio' => 'CONDOMINIO LOCAL L-11',
                'empresa' => 'A.S. 20 PARAGUANÁ, C.A.',
                'fecha' => '31 - 15 de cada mes',
                'costo' => 800,
                'orden' => 50,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'NUNES STORE, C.A. J501653879',
                'servicio' => 'INTERNET LOCAL L-11',
                'empresa' => 'BESSER SOLUTIONS',
                'fecha' => '15',
                'costo' => 35,
                'orden' => 47,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'NUNES STORE, C.A. J501653879',
                'servicio' => 'MONITOREO Y SOPORTE SERVIDOR',
                'empresa' => 'INFORMATICA UNIX',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 25,
                'orden' => 51,
                'visible' => true,
            ],
            [
                'grupo_id' => 1,
                'sede' => 'NUNES STORE, C.A. J501653879',
                'servicio' => 'RECARGA TELEFONO ENCARGADO NUNES',
                'empresa' => 'NUNES STORE',
                'fecha' => '17',
                'costo' => 0.5,
                'orden' => 48,
                'visible' => true,
            ],
            [
                'grupo_id' => 2,
                'sede' => 'GALPON BELLA VISTA V32089692',
                'servicio' => 'INTERNET GALPON',
                'empresa' => 'AIRTEK',
                'fecha' => '1 - 5 de cada mes',
                'costo' => 30,
                'orden' => 60,
                'visible' => true,
            ],
        ];

        foreach ($gastos as $gasto) {
            GastoFijo::create($gasto);
        }
    }
}
