<?php

namespace Database\Seeders;

use App\Models\Cliente;
use App\Models\Nomina\NominaCargo;
use App\Models\Nomina\NominaEmpleado;
use App\Models\Nomina\NominaEmpleadoVendedor;
use App\Models\Nomina\NominaSede;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class NominaPersonalSeeder extends Seeder
{
    public function run(): void
    {
        $this->call(NominaCatalogSeeder::class);
        $sedes = NominaSede::query()->get()->keyBy('codigo');
        $cargos = NominaCargo::query()->get()->keyBy('nombre');

        foreach (self::personal() as $fila) {
            $this->upsertEmpleado($fila, $sedes, $cargos);
        }

        $porCedula = NominaEmpleado::query()->with('cliente')->get()
            ->keyBy(fn (NominaEmpleado $e) => $e->cedula());

        foreach (self::personal() as $fila) {
            $this->asignarJefes($fila, $porCedula);
            $this->asignarVendedor($fila, $porCedula);
        }
    }

    /**
     * @param  array<string, mixed>  $fila
     * @param  \Illuminate\Support\Collection<string, NominaSede>  $sedes
     * @param  \Illuminate\Support\Collection<string, NominaCargo>  $cargos
     */
    private function upsertEmpleado(array $fila, $sedes, $cargos): void
    {
        $sede = $sedes->get($fila['sede']);
        $cargo = $fila['cargo'] ? $cargos->get($fila['cargo']) : null;

        $cliente = Cliente::query()->updateOrCreate(
            ['cedula' => $fila['cedula']],
            ['nombre' => $fila['nombre']]
        );

        $empleado = NominaEmpleado::query()->firstOrNew(['cliente_id' => $cliente->id]);
        $empleado->sede_id = $sede?->id;
        $empleado->sede = $fila['sede'];
        $empleado->cargo_id = $cargo?->id;
        $empleado->cargo = $fila['cargo'] ?? $empleado->cargo;
        $empleado->fecha_ingreso = $fila['ingreso'] ?: $empleado->fecha_ingreso;
        $empleado->estado = $fila['estado'] ?? 'ACTIVO';
        $empleado->email = $fila['email'] ?: null;
        $empleado->telefono = $fila['telefono'] ?: null;
        $empleado->salario_base = $fila['salario'];
        $empleado->tipo_salario = $fila['tipo_salario'] ?? 'MENSUAL';
        $empleado->es_servicio_tecnico = ($fila['cargo'] ?? '') === 'Servicio técnico';
        $empleado->es_supervisor = $this->esCargoSupervisor($fila['cargo'] ?? null);
        $empleado->modo_comision = $this->modoInicial($fila['cargo'] ?? null);
        $empleado->codigo_vendedor = NominaEmpleado::normalizarVendedor($fila['codigo_vendedor'] ?? null);
        $empleado->save();
    }

    /**
     * @param  array<string, mixed>  $fila
     * @param  \Illuminate\Support\Collection<string, NominaEmpleado>  $porCedula
     */
    private function asignarJefes(array $fila, $porCedula): void
    {
        $empleado = $porCedula->get($fila['cedula']);
        if (! $empleado) {
            return;
        }

        $ids = [];
        foreach ($fila['jefes'] ?? [] as $cedulaJefe) {
            $jefe = $porCedula->get($cedulaJefe);
            if ($jefe && $jefe->id !== $empleado->id) {
                $jefe->es_supervisor = true;
                $jefe->save();
                $ids[] = $jefe->id;
            }
        }

        $ids = array_values(array_unique($ids));
        $empleado->supervisor_id = $ids[0] ?? null;
        $empleado->save();

        if (Schema::hasTable('nomina_empleado_supervisores')) {
            $empleado->jefes()->sync($ids);
        }
    }

    /**
     * @param  array<string, mixed>  $fila
     * @param  \Illuminate\Support\Collection<string, NominaEmpleado>  $porCedula
     */
    private function asignarVendedor(array $fila, $porCedula): void
    {
        $empleado = $porCedula->get($fila['cedula']);
        if (! $empleado || ! Schema::hasTable('nomina_empleado_vendedores')) {
            return;
        }

        $principal = $empleado->codigoVendedor();
        foreach ($fila['aliases'] ?? [] as $alias) {
            $alias = NominaEmpleado::normalizarVendedor($alias);
            if (! $alias || $alias === $principal) {
                continue;
            }

            $tomado = NominaEmpleado::query()
                ->whereRaw('UPPER(TRIM(codigo_vendedor)) = ?', [$alias])
                ->where('id', '!=', $empleado->id)
                ->exists();
            if ($tomado) {
                continue;
            }

            NominaEmpleadoVendedor::query()->updateOrCreate(
                ['nombre_normalizado' => $alias],
                [
                    'empleado_id' => $empleado->id,
                    'nombre_vendedor' => $alias,
                    'codigo_profit' => $alias,
                ]
            );
        }
    }

    private function esCargoSupervisor(?string $cargo): bool
    {
        $cargo = (string) $cargo;

        return str_contains($cargo, 'Supervisor')
            || str_contains($cargo, 'Supervisora')
            || str_contains($cargo, 'Coordinador')
            || str_contains($cargo, 'Líder de tienda')
            || $cargo === 'Gerente';
    }

    private function modoInicial(?string $cargo): string
    {
        return match (true) {
            $cargo === 'Servicio técnico' => NominaEmpleado::COMISION_SERVICIO_TECNICO,
            $cargo === 'Supervisor de sede',
            $cargo === 'Líder de tienda senior' => NominaEmpleado::COMISION_SUPERVISOR_SEDE,
            $cargo === 'Supervisora área call center' => NominaEmpleado::COMISION_SUPERVISOR_EQUIPO,
            str_contains((string) $cargo, 'Asesor')
                || in_array($cargo, ['PCP', 'Call center'], true) => NominaEmpleado::COMISION_VENTAS_PROPIAS,
            default => NominaEmpleado::COMISION_NINGUNA,
        };
    }

    /**
     * Snapshot de producción local (fichas + códigos de vendedor Profit).
     *
     * @return list<array<string, mixed>>
     */
    public static function personal(): array
    {
        return [
            [
                'cedula' => '19648944',
                'nombre' => 'CARLOS JAVIER GOMEZ JIMENEZ',
                'sede' => 'CENTRO',
                'cargo' => 'Supervisor de sede',
                'ingreso' => '2024-08-09',
                'jefes' => ['AURILES'],
                'salario' => 450,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'CARLOS GOMEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28501943',
                'nombre' => 'GEOVANNI JESUS GUTIERREZ MARTINEZ',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta telefonía',
                'ingreso' => '2022-04-28',
                'jefes' => ['19648944'],
                'salario' => 180,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'GIOVANNY GUTIERREZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '18479961',
                'nombre' => 'FRANCISCO JAVIER AULAR ESCOCHE',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-10-04',
                'jefes' => ['19648944'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'FRANCISCO AULAR',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31422012',
                'nombre' => 'JHATARY MARGARET LUQUES DAVILA',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-05-20',
                'jefes' => ['19648944'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JATHARY LUQUES',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32431800',
                'nombre' => 'DANIELA ALEJANDRA DIAZ DIAZ',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-12-07',
                'jefes' => ['19648944'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'DANIELA DIAZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31234942',
                'nombre' => 'GABRIELA VALENTINA GARCIA HERNANDEZ',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-12-09',
                'jefes' => ['19648944'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'GRABIELA GARCIA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28766449',
                'nombre' => 'AMBAR REBECA CUAURO CHIQUITO',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-05-11',
                'jefes' => ['19648944'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'AMBAR CUAURO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31475493',
                'nombre' => 'YOSILIS ALEXANDRA LUGO BRACHO',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-05-21',
                'jefes' => ['19648944'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'YOSILIS LUGO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28369045',
                'nombre' => 'JOSEMAR DEL CARMEN MAVAREZ LUGO',
                'sede' => 'CALL_CENTER',
                'cargo' => 'Call center',
                'ingreso' => '2026-06-16',
                'jefes' => ['28382238'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JOSEMAR',
                'aliases' => ['JOSEMAR MAVAREZ'],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28771171',
                'nombre' => 'WENDY KAROLINA AÑEZ MATOS',
                'sede' => 'INVENTARIO',
                'cargo' => 'Analista de inventario',
                'ingreso' => '2026-02-26',
                'jefes' => ['30657986'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'WENDY AÑEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31560045',
                'nombre' => 'JOSMARLIN CAROLINA QUERO GUASAMUCARE',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-04-30',
                'jefes' => ['19648944'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'CAROLINA QUERO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '34430262',
                'nombre' => 'IRAIDA DEL CARMEN GOMEZ SANCHEZ',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-07-23',
                'jefes' => ['19648944'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'IRAIDA GOMEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '26598293',
                'nombre' => 'JOSMARLY ANDREINA VELAZQUEZ PRIMERA',
                'sede' => 'VIRTUDES',
                'cargo' => 'Supervisor de sede',
                'ingreso' => '2024-04-29',
                'jefes' => ['AURILES'],
                'salario' => 450,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JOSMARLYN VELASQUEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '26930051',
                'nombre' => 'JORGE LUIS DIAZ LOPEZ',
                'sede' => 'CENTRO',
                'cargo' => 'Servicio técnico',
                'ingreso' => '2026-04-18',
                'jefes' => ['19648944'],
                'salario' => 250,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JORGE DIAZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32553909',
                'nombre' => 'DANIEL ALEJANDRO SARMIENTO LOPEZ',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta telefonía',
                'ingreso' => '2026-04-13',
                'jefes' => ['19648944'],
                'salario' => 160,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'DANIEL SARMIENTO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '27811139',
                'nombre' => 'FREYGLING ALBERTO SANCHEZ SALAS',
                'sede' => 'GERENCIA',
                'cargo' => 'Coordinador de tienda',
                'ingreso' => '2022-03-27',
                'jefes' => ['AURILES'],
                'salario' => 580,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32565039',
                'nombre' => 'MARIANGELA DIAZ',
                'sede' => 'EGRESOS',
                'cargo' => null,
                'ingreso' => null,
                'jefes' => [],
                'salario' => 0,
                'tipo_salario' => 'QUINCENAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '30248629',
                'nombre' => 'EMILY NAZARETH PULGAR NAVARRO',
                'sede' => 'ZAMORA',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-04-22',
                'jefes' => ['19944238', '18426259'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'EMILY PULGAR',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31629058',
                'nombre' => 'GEORGINA DEL VALLE ZAVALA SANCHEZ',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-05-06',
                'jefes' => ['28369458'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'YORGINA ZAVALA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '25010760',
                'nombre' => 'ANGEL ANTONIO JIMENEZ CALDERA',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta telefonía',
                'ingreso' => '2025-11-27',
                'jefes' => ['28369458'],
                'salario' => 160,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'ANGEL JIMENEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28695505',
                'nombre' => 'ANDREA COROMOTO CHIQUITO TESTA',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-12-11',
                'jefes' => ['28369458'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'ANDREA CHIQUITO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '27273261',
                'nombre' => 'YORGELIS DANIELA ROMAN MIRANDA',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-05-06',
                'jefes' => ['28369458'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'YORGELIS ROMÁN',
                'aliases' => ['YORGELIS ROMAN'],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31603843',
                'nombre' => 'DANIBEI ANDREINA DE ALMEIDA BRACHO',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-04-23',
                'jefes' => ['28369458'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'DANIBET DE ALMEIDA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31852005',
                'nombre' => 'JUAN PABLO BEAUJON BLANCO',
                'sede' => 'VIRTUDES',
                'cargo' => 'PCP',
                'ingreso' => '2026-04-17',
                'jefes' => ['26598293', '25402263'],
                'salario' => 200,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JUAN PABLO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28772921',
                'nombre' => 'WANDA GABRIELA VENTURA SANCHEZ',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-04-28',
                'jefes' => ['28369458'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'WANDA VENTURA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28776417',
                'nombre' => 'ISAMAR ELIANGELES ROMAN ARCAYA',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-07-21',
                'jefes' => ['28369458'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'ISAMAR ROMAN',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '27924198',
                'nombre' => 'YESSICA JULIANNA SOUSA BRACHO',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-06-15',
                'jefes' => ['28369458'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'YESSICA SOSA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '26656789',
                'nombre' => 'JOSE DANIEL SENIOR',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta telefonía',
                'ingreso' => '2025-11-04',
                'jefes' => ['28369458'],
                'salario' => 160,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'DANIEL SENIOR',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28340171',
                'nombre' => 'MELANNY REBECA CARRASQUERO CUAURO',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-04-28',
                'jefes' => ['28369458'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'MELANY CARRASQUERO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28369458',
                'nombre' => 'ALEJANDRA PAOLA SALAS DIAZ',
                'sede' => 'DORAL',
                'cargo' => 'Supervisor de sede',
                'ingreso' => '2024-05-06',
                'jefes' => ['AURILES'],
                'salario' => 450,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'ALEJANDRA SALAS',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '18426259',
                'nombre' => 'ANDRES EDUARDO QUEVEDO RAMIREZ',
                'sede' => 'ZAMORA',
                'cargo' => 'Supervisor de sede',
                'ingreso' => '2024-03-13',
                'jefes' => ['AURILES'],
                'salario' => 450,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'ANDRÉS QUEVEDO',
                'aliases' => ['ANDRES QUEVEDO'],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '33055326',
                'nombre' => 'SARAH VALENTINA GRATEROL ROMERO',
                'sede' => 'ZAMORA',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-09-23',
                'jefes' => ['19944238', '18426259'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'SARAH GRATEROL',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '27844739',
                'nombre' => 'IVANIA ROSA DE LAS MERCEDES SANCHEZ RAMIREZ',
                'sede' => 'ZAMORA',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-03-11',
                'jefes' => ['19944238', '18426259'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'IVANIA SANCHEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31446406',
                'nombre' => 'ADRIANNY ISABEL MARTINEZ POLANCO',
                'sede' => 'ZAMORA',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2024-11-01',
                'jefes' => ['19944238', '18426259'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'ADRIANNYS MARTINEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28769767',
                'nombre' => 'JHONAISY DELIMAR NAVAS ROSENDO',
                'sede' => 'ZAMORA',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-02-06',
                'jefes' => ['19944238', '18426259'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JHONAISY NAVAS',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28769916',
                'nombre' => 'ANDRUELYS PAOLA HURTADO GAMEZ',
                'sede' => 'ZAMORA',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-06-17',
                'jefes' => ['19944238', '18426259'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'AUDRELYS HURTADO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '27420927',
                'nombre' => 'JAVIER JESUS LEAL RAMIREZ',
                'sede' => 'INVENTARIO',
                'cargo' => 'Analista de inventario',
                'ingreso' => '2026-07-09',
                'jefes' => ['30657986'],
                'salario' => 250,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JAVIER LEAL',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31629048',
                'nombre' => 'JHOSMARLYN GUADALUPE SANCHEZ MUJICA',
                'sede' => 'ZAMORA',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-07-29',
                'jefes' => ['19944238', '18426259'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JHOSMARILYN SANCHEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '23675095',
                'nombre' => 'OSWALDO JOSE BERMUDEZ REINALES',
                'sede' => 'ZAMORA',
                'cargo' => 'Asesor de venta telefonía',
                'ingreso' => '2026-03-26',
                'jefes' => ['19944238', '18426259'],
                'salario' => 160,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'OSWALDO BERMUDEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '27420921',
                'nombre' => 'OSCAR PALOMO',
                'sede' => 'SAMBIL',
                'cargo' => 'Supervisor de sede',
                'ingreso' => '2021-11-27',
                'jefes' => ['AURILES'],
                'salario' => 250,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31234681',
                'nombre' => 'JORGELIS MARIA VELASQUEZ GARCIA',
                'sede' => 'SAMBIL',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-01-03',
                'jefes' => ['27420921'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JORGELIS VELAQUEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '19944238',
                'nombre' => 'FRANCIS DEL VALLE MARIN DELGADO',
                'sede' => 'ZAMORA',
                'cargo' => 'Supervisor de sede',
                'ingreso' => '2025-08-21',
                'jefes' => ['AURILES'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'FRANCIS MARIN',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '26309612',
                'nombre' => 'OCTAVIO ENRIQUE LUGO MALDONADO',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta telefonía',
                'ingreso' => '2024-07-18',
                'jefes' => ['26598293', '25402263'],
                'salario' => 160,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'OCTAVIO LUGO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32247446',
                'nombre' => 'HANNAD ROBERTIS',
                'sede' => 'MOVISTAR',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-10-19',
                'jefes' => ['AURILES'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'HANNA ROBERTIS',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '33600138',
                'nombre' => 'HADZAY IXCHEL VENTURA RONDON',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-01-19',
                'jefes' => ['26598293', '25402263'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'HADZAY VENTURA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31489611',
                'nombre' => 'BRISNEIDYS SALAZAR',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-03-20',
                'jefes' => ['26598293', '25402263'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'BRISNEIDYS SALAZAR',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31789963',
                'nombre' => 'CARLOS EDUARDO REYES GONZALEZ',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta telefonía',
                'ingreso' => '2026-03-11',
                'jefes' => ['26598293', '25402263'],
                'salario' => 160,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'CARLOS REYES',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '16439637',
                'nombre' => 'DEYBE JUNIOR ZAMBRANO MEDINA',
                'sede' => 'VIRTUDES',
                'cargo' => 'Servicio técnico',
                'ingreso' => '2025-07-28',
                'jefes' => ['26598293', '25402263'],
                'salario' => 300,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31240573',
                'nombre' => 'VALENTINA VICTORIA MARIN MUJICA',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-07-24',
                'jefes' => ['26598293', '25402263'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'VALENTINA MARÍN',
                'aliases' => ['VALENTINA MARIN'],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '30490783',
                'nombre' => 'MARIARGEN HEFZIBA ZAVARCE GARCIA',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-07-22',
                'jefes' => ['26598293', '25402263'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'MARIAGERM ZARVACE',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '30490950',
                'nombre' => 'CARLOS MENDEZ',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2025-09-24',
                'jefes' => ['26598293', '25402263'],
                'salario' => 190,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'CARLOS MENDEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31901317',
                'nombre' => 'ISLENIA VICTORIA NARANJO MYKOO',
                'sede' => 'MARKETING',
                'cargo' => 'Community manager',
                'ingreso' => '2023-04-10',
                'jefes' => ['28369203'],
                'salario' => 200,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28382238',
                'nombre' => 'MARIA GABRIELA MARTINEZ PETIT',
                'sede' => 'CALL_CENTER',
                'cargo' => 'Supervisora área call center',
                'ingreso' => '2025-06-17',
                'jefes' => ['AURILES'],
                'salario' => 230,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'MARIA PETIT',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31943520',
                'nombre' => 'MARIA VIRGINIA RAMONES NIÑO',
                'sede' => 'MARKETING',
                'cargo' => 'Community manager',
                'ingreso' => '2025-06-16',
                'jefes' => ['28369203'],
                'salario' => 160,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'MARIA RAMONES',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28723018',
                'nombre' => 'BARBARA DE LOS ANGELES LOPEZ ROJAS',
                'sede' => 'CALL_CENTER',
                'cargo' => 'Call center',
                'ingreso' => '2026-04-21',
                'jefes' => ['28382238'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'BARBARA LOPEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32689028',
                'nombre' => 'EILEEN KATIELLA ABREU GERMAN',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-04-14',
                'jefes' => ['19648944'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'EILEEN ABREU',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '25470483',
                'nombre' => 'ABEL DAVID YAJURIS BALDALLO',
                'sede' => 'MARKETING',
                'cargo' => 'Community manager',
                'ingreso' => '2026-05-14',
                'jefes' => ['28369203'],
                'salario' => 200,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'ABEL YAJURIS',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28046742',
                'nombre' => 'JAIR ALEXANDER AVILA',
                'sede' => 'CALL_CENTER',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-03-31',
                'jefes' => ['28382238'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JAIR AVILA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '22898423',
                'nombre' => 'EDWAR RAFEL MAVO GARCIA',
                'sede' => 'COMPRAS',
                'cargo' => null,
                'ingreso' => '2022-03-27',
                'jefes' => ['AURILES'],
                'salario' => 600,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '21155688',
                'nombre' => 'PAOLA CRISTINA COLINA NAVAS',
                'sede' => 'COMPRAS',
                'cargo' => null,
                'ingreso' => '2024-03-11',
                'jefes' => ['AURILES'],
                'salario' => 600,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '20552705',
                'nombre' => 'MARIA ALEJANDRA POLANCO NAVAS',
                'sede' => 'CONTABILIDAD',
                'cargo' => 'Analista contable tributario',
                'ingreso' => '2026-04-20',
                'jefes' => ['AURILES'],
                'salario' => 300,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '16198138',
                'nombre' => 'CARLOS ALBERTO RUIZ CASTILLO',
                'sede' => 'CONTABILIDAD',
                'cargo' => null,
                'ingreso' => '2024-04-09',
                'jefes' => ['AURILES'],
                'salario' => 500,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32027142',
                'nombre' => 'DAGMAR ALEXANDRA JEREZ BERRIOS',
                'sede' => 'ADMINISTRACION',
                'cargo' => 'Analista administrativo',
                'ingreso' => '2024-03-01',
                'jefes' => ['AURILES'],
                'salario' => 280,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28369203',
                'nombre' => 'PATRICIA MARIA COLINA NAVAS',
                'sede' => 'MARKETING',
                'cargo' => null,
                'ingreso' => '2018-01-01',
                'jefes' => ['AURILES'],
                'salario' => 500,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'PATRICIA COLINA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '24305868',
                'nombre' => 'GUSMALYS MARIANNIS MEDINA VELAZQUES',
                'sede' => 'TESORERIA',
                'cargo' => null,
                'ingreso' => '2021-04-19',
                'jefes' => ['AURILES'],
                'salario' => 500,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '26058100',
                'nombre' => 'JOSE FRANCISCO SEMECO CHIRINOS',
                'sede' => 'FINANZAS',
                'cargo' => null,
                'ingreso' => '2024-03-01',
                'jefes' => ['AURILES'],
                'salario' => 500,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '24306562',
                'nombre' => 'DAYANA ALEJANDRA LOPEZ DIAZ',
                'sede' => 'CUENTAS_COBRAR',
                'cargo' => 'Analista administrativo',
                'ingreso' => '2023-09-02',
                'jefes' => ['AURILES'],
                'salario' => 400,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => '04127648158',
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '17500110',
                'nombre' => 'DIANA CAROLINA BUSTILLO CASTRO',
                'sede' => 'RRHH',
                'cargo' => 'Coordinadora de RRHH',
                'ingreso' => '2024-02-21',
                'jefes' => ['AURILES'],
                'salario' => 550,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '18632452',
                'nombre' => 'CARLOS ISAIAS SEMECO GOMEZ',
                'sede' => 'COMPRAS',
                'cargo' => null,
                'ingreso' => '2025-07-16',
                'jefes' => ['AURILES'],
                'salario' => 600,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28715593',
                'nombre' => 'VALENTINA JULIETH GONZALEZ MARTINEZ',
                'sede' => 'MARKETING',
                'cargo' => null,
                'ingreso' => '2023-09-29',
                'jefes' => ['28369203'],
                'salario' => 270,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'VALENTINA GONZALEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28766068',
                'nombre' => 'MIGUEL LEONARDO AULAR ARRIETA',
                'sede' => 'ADMINISTRACION',
                'cargo' => null,
                'ingreso' => '2026-04-09',
                'jefes' => ['AURILES'],
                'salario' => 300,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'MIGUEL AULAR (MERCADOLIBRE)',
                'aliases' => [],
                'email' => 'miguelaular17@gmail.com',
                'telefono' => '04127671472',
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '26058437',
                'nombre' => 'JOSEPH ROBERT BRACHO VILLANUEVA',
                'sede' => 'SOPORTE_TECNICO',
                'cargo' => null,
                'ingreso' => '2025-12-06',
                'jefes' => ['AURILES'],
                'salario' => 270,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '26218256',
                'nombre' => 'MANUEL JUNIOR RUIZ REYNA',
                'sede' => 'INVENTARIO',
                'cargo' => 'Analista de inventario',
                'ingreso' => '2024-04-09',
                'jefes' => ['30657986'],
                'salario' => 320,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '25402263',
                'nombre' => 'BRANDON SANCHEZ',
                'sede' => 'VIRTUDES',
                'cargo' => 'Supervisor de sede',
                'ingreso' => '2026-04-24',
                'jefes' => [],
                'salario' => 250,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'BRANDON SÁNCHEZ',
                'aliases' => ['BRANDON SANCHEZ'],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '30657986',
                'nombre' => 'RICARDO DAVID GIMENEZ PAEZ',
                'sede' => 'INVENTARIO',
                'cargo' => 'Supervisor de inventario',
                'ingreso' => '2024-10-09',
                'jefes' => ['AURILES'],
                'salario' => 450,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '20796305',
                'nombre' => 'ISAAC TORO',
                'sede' => 'INVENTARIO',
                'cargo' => 'Analista de inventario',
                'ingreso' => '2024-05-16',
                'jefes' => ['30657986'],
                'salario' => 280,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '20797535',
                'nombre' => 'JONATHAN SANCHEZ',
                'sede' => 'DEPOSITO',
                'cargo' => 'Coordinador logístico',
                'ingreso' => '2024-09-29',
                'jefes' => ['AURILES'],
                'salario' => 450,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32453733',
                'nombre' => 'OTONIEL DAVID SARMIENTO ALVARADO',
                'sede' => 'DEPOSITO',
                'cargo' => 'Receptor de mercancía',
                'ingreso' => '2026-03-02',
                'jefes' => ['20797535'],
                'salario' => 250,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28679958',
                'nombre' => 'ANDRES VELASCO',
                'sede' => 'SAMBIL',
                'cargo' => 'Asesor de venta telefonía',
                'ingreso' => '2026-03-18',
                'jefes' => ['19944238', '18426259'],
                'salario' => 250,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31508033',
                'nombre' => 'RAMIRO ANTONIO COELLO RUIZ',
                'sede' => 'DEPOSITO',
                'cargo' => 'Receptor de mercancía',
                'ingreso' => '2026-07-20',
                'jefes' => ['20797535'],
                'salario' => 250,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '24166691',
                'nombre' => 'LUIS GARCIA',
                'sede' => 'FLOTA',
                'cargo' => 'Chofer',
                'ingreso' => '2005-12-11',
                'jefes' => ['9510978'],
                'salario' => 400,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '25126829',
                'nombre' => 'JOSE DANIEL MOLINA ARTEAGA',
                'sede' => 'FLOTA',
                'cargo' => 'Chofer',
                'ingreso' => '2025-10-29',
                'jefes' => ['9510978'],
                'salario' => 400,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '9510978',
                'nombre' => 'GREGORIO JOSE COLINA AÑEZ',
                'sede' => 'FLOTA',
                'cargo' => 'Supervisor de flota',
                'ingreso' => '2020-12-01',
                'jefes' => ['27811139'],
                'salario' => 260,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '14478485',
                'nombre' => 'JOHAN LANOI',
                'sede' => 'MANTENIMIENTO',
                'cargo' => 'Operador de mantenimiento',
                'ingreso' => '2025-01-01',
                'jefes' => ['9510978'],
                'salario' => 400,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '14208321',
                'nombre' => 'FAUSTO JUNIOR GOITIA OBERTO',
                'sede' => 'MANTENIMIENTO',
                'cargo' => 'Operador de mantenimiento',
                'ingreso' => '2026-07-27',
                'jefes' => ['9510978'],
                'salario' => 300,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31536274',
                'nombre' => 'JOHAN ALEJANDRO',
                'sede' => 'MANTENIMIENTO',
                'cargo' => 'Operador de mantenimiento',
                'ingreso' => '2025-01-01',
                'jefes' => ['9510978'],
                'salario' => 240,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31930120',
                'nombre' => 'MARIA SALERO',
                'sede' => 'NUNES',
                'cargo' => 'Supervisor de sede',
                'ingreso' => '2024-09-17',
                'jefes' => ['AURILES'],
                'salario' => 220,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28767172',
                'nombre' => 'VICTOR ENRIQUE RODRIGUEZ POLANCO',
                'sede' => 'DEPOSITO',
                'cargo' => 'Receptor de mercancía',
                'ingreso' => '2026-08-12',
                'jefes' => ['20797535'],
                'salario' => 250,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '28026549',
                'nombre' => 'ANA CRISTINA RODRIGUEZ QUIJANO',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-08-05',
                'jefes' => ['28369458'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'ANA RODRIGUEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32688831',
                'nombre' => 'GERARDO JOSE ATACHO FALCON',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-07-27',
                'jefes' => ['28369458'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'GERARDO ATACHO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32531659',
                'nombre' => 'JEULIMAR MEDINA',
                'sede' => 'DORAL',
                'cargo' => 'Asesor de venta',
                'ingreso' => null,
                'jefes' => ['28369458'],
                'salario' => 0,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JEULIMAR MEDINA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32443525',
                'nombre' => 'EMILIO MAURICIO CASTRILLO PARRA',
                'sede' => 'ZAMORA',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-08-10',
                'jefes' => ['19944238', '18426259'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'EMILIO CASTRILLO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '30059313',
                'nombre' => 'MARIANGEL JOSEFINA ZAMARRIPA PALENCIA',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-08-07',
                'jefes' => ['26598293', '25402263'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'MARIANGEL ZAMARRIPA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '26723116',
                'nombre' => 'VALERY THARAMA MARQUEZ GUTIERREZ',
                'sede' => 'CALL_CENTER',
                'cargo' => 'Call center',
                'ingreso' => '2026-08-07',
                'jefes' => ['28382238'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'VALERY MÁRQUEZ',
                'aliases' => ['VALERY MARQUEZ'],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '31447163',
                'nombre' => 'JETSY ALBANI NAVARRO VARGAS',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-08-05',
                'jefes' => ['26598293', '25402263'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'JETSY NAVARRO',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32453764',
                'nombre' => 'MADELEINE JULIANNIS MORALES GALBAN',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-08-04',
                'jefes' => ['26598293', '25402263'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'MADELEINE MORALES',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '32144295',
                'nombre' => 'FRANNELVIS EIMAR PEREIRA MATA',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-08-05',
                'jefes' => ['26598293', '25402263'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'FRANNELVIS PEREIRA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '30892751',
                'nombre' => 'EMMA MARIA SANCHEZ ARRIECHE',
                'sede' => 'VIRTUDES',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-08-09',
                'jefes' => ['26598293', '25402263'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'EMMA SANCHEZ',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '25402089',
                'nombre' => 'YINMAIRI BEATRIZ MORA CASTRO',
                'sede' => 'CENTRO',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-08-08',
                'jefes' => ['19648944'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'YINMAIRY MORA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => 'AURILES',
                'nombre' => 'AURILES LUGO',
                'sede' => 'GERENCIA',
                'cargo' => 'Gerente',
                'ingreso' => null,
                'jefes' => [],
                'salario' => 0,
                'tipo_salario' => 'QUINCENAL',
                'codigo_vendedor' => null,
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '33789656',
                'nombre' => 'VALERY DANIELA CHAVEZ MEDINA',
                'sede' => 'ZAMORA',
                'cargo' => 'Asesor de venta',
                'ingreso' => '2026-06-18',
                'jefes' => ['19944238', '18426259'],
                'salario' => 170,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'VALERY CHAVES',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
            [
                'cedula' => '25848623',
                'nombre' => 'KEISY DAYANA DA SILVA CALLES',
                'sede' => 'CENTRO',
                'cargo' => 'Supervisor de sede',
                'ingreso' => '2026-08-13',
                'jefes' => ['AURILES'],
                'salario' => 250,
                'tipo_salario' => 'MENSUAL',
                'codigo_vendedor' => 'KEISY DA SILVA',
                'aliases' => [],
                'email' => null,
                'telefono' => null,
                'estado' => 'ACTIVO',
            ],
        ];
    }
}
