<?php

return [
    /*
     * Permisos asignables a un usuario además de su rol.
     * admin y gerente tienen todos (se resuelve en User::canAccess).
     */
    'assignable' => [
        'operacion' => 'Operación (ventas, inventario, exportar)',
        'compras' => 'Compras / Marketing (todas las tablas)',
        'compras.distribucion' => 'Compras: Distribución',
        'compras.necesidad' => 'Compras: Necesidad de compra',
        'compras.proveedores' => 'Compras: General por proveedor',
        'compras.sobrestock' => 'Compras: Sobre stock / sin rotación',
        'compras.qpedir' => 'Compras: Q Pedir',
        'compras.existencias' => 'Compras: Existencias globales',
        'compras.publicidad' => 'Compras: Efectividad publicidad',
        'compras.reporte_sede' => 'Reporte diario de pedidos por sede',
        'catalogo.existencias' => 'Catálogo: tabla de stock (existencias por sede)',
        'catalogo.precios' => 'Catálogo: ver precios y Cashea',
        'catalogo.exportar_precios' => 'Catálogo: descargar Excel de precios con descuento',
        'vendedor.jrz' => 'Vendedor en JRZ (stock + ventas por sede)',
        'finanzas.ver' => 'Flujo de caja, cuentas por pagar y gastos fijos (ver)',
        'finanzas.editar' => 'Flujo de caja, cuentas por pagar y gastos fijos (editar)',
        'finanzas.eliminar' => 'Eliminar egresos, traslados, divisas y avances',
        'conciliaciones' => 'Conciliaciones',
        'tesoreria' => 'Tesorería',
        'cobranza' => 'Cobranza',
        'contratos' => 'Contratos',
        'patrimonial' => 'Patrimonial',
        'nomina' => 'Nómina',
        'nomina.equipo' => 'Nómina y comisiones del equipo (tras calcular)',
        'marketing.publicidad_equipo' => 'Ver publicidad del equipo',
        'meta' => 'Metas de quincena (marcar productos)',
        'meta.ver' => 'Metas de quincena (solo ver / supervisor)',
        'gerencial' => 'Dashboard gerencial',
        'gerencial.devoluciones' => 'Devoluciones en ventas',
        'gerencial.valorizados' => 'Valorizados de inventarios',
        'gerencial.ajustes' => 'Consolidados de ajustes de inventarios',
        'gerencial.rentabilidad' => 'Rentabilidad gerencial',
        'gerencial.clientes' => 'Clientes por sede (facturas, unidades y montos)',
        'servicio' => 'Servicio técnico',
        'servicio.inventario' => 'Inventario de repuestos (servicio técnico)',
        'servicio.transferir' => 'Transferir celulares / órdenes entre sedes',
        'nfc' => 'Tarjetas NFC (asignar y fichas de cliente)',
    ],

    /*
     * Secciones usadas para presentar los permisos en la administración.
     * Las claves deben existir en "assignable".
     */
    'groups' => [
        'Operaciones' => ['operacion', 'catalogo.existencias', 'catalogo.precios', 'catalogo.exportar_precios', 'vendedor.jrz'],
        'Compras y Marketing' => [
            'compras',
            'compras.distribucion',
            'compras.necesidad',
            'compras.proveedores',
            'compras.sobrestock',
            'compras.qpedir',
            'compras.existencias',
            'compras.publicidad',
            'marketing.publicidad_equipo',
            'meta',
            'meta.ver',
        ],
        'Reportes' => ['compras.reporte_sede'],
        'Finanzas' => ['finanzas.ver', 'finanzas.editar', 'finanzas.eliminar'],
        'Conciliaciones bancarias' => ['conciliaciones'],
        'Tesorería' => ['tesoreria'],
        'Cobranza' => ['cobranza'],
        'Contratos' => ['contratos'],
        'Patrimonial' => ['patrimonial'],
        'Nómina' => ['nomina', 'nomina.equipo'],
        'Gerencial' => ['gerencial', 'gerencial.devoluciones', 'gerencial.valorizados', 'gerencial.ajustes', 'gerencial.rentabilidad', 'gerencial.clientes'],
        'Servicio técnico' => ['servicio', 'servicio.inventario', 'servicio.transferir'],
        'Tarjetas NFC' => ['nfc'],
    ],

    'roles' => [
        'admin' => ['*'],
        'gerente' => ['*'],
        'supervisor' => ['operacion', 'compras.reporte_sede'],
        'telefonia' => ['operacion'],
        'sede' => ['operacion'],
        'comprador' => ['operacion', 'compras'],
        'marketing' => ['compras'],
        'finanzas' => ['finanzas.ver', 'finanzas.editar', 'finanzas.eliminar'],
        'auditor' => ['finanzas.ver'],
        'contabilidad' => ['conciliaciones'],
        'cobranza' => ['cobranza', 'contratos', 'patrimonial'],
        'tesoreria' => ['tesoreria'],
        'rrhh' => ['nomina'],
        'tecnico' => ['servicio'],
        'vendedor' => [],
    ],
];
